# Generated by Django 3.1.7 on 2021-03-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description_short', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Описание')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта')),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
